# ADK Configuration for DLQ Monitor System

# General ADK settings
adk:
  name: "DLQ Monitor System"
  version: "1.0.0"
  description: "Multi-agent system for monitoring and auto-fixing DLQ issues"
  
# Model configuration
model:
  provider: "gemini"
  default_model: "gemini-2.0-flash"
  temperature: 0.7
  max_tokens: 4096
  
# Agent orchestration settings
orchestration:
  mode: "hierarchical"
  max_parallel_agents: 3
  timeout_seconds: 300
  retry_attempts: 3
  
# Monitoring configuration
monitoring:
  check_interval_seconds: 30
  dlq_patterns:
    - "-dlq"
    - "-dead-letter"
    - "-deadletter"
    - "_dlq"
    - "-dl"
  auto_investigate_dlqs:
    - "fm-digitalguru-api-update-dlq-prod"
    - "fm-transaction-processor-dlq-prd"
  investigation_cooldown_seconds: 3600  # 1 hour
  
# AWS Configuration
aws:
  profile: "FABIO-PROD"
  region: "sa-east-1"
  account_id: ""  # Will be fetched dynamically
  
# GitHub Configuration
github:
  repo_owner: "fabio-lpd"
  repo_name: "lpd-claude-code-monitor"
  default_branch: "main"
  pr_labels:
    - "auto-investigation"
    - "dlq-fix"
    - "production"
  
# Notification settings
notifications:
  enable_macos: true
  enable_voice: true
  voice_provider: "elevenlabs"
  pr_reminder_interval_seconds: 600  # 10 minutes
  critical_alert_sound: true
  
# Logging configuration
logging:
  level: "INFO"
  format: "json"
  file: "logs/adk_monitor.log"
  max_size_mb: 100
  backup_count: 5
  
# Session management
session:
  persist_state: true
  state_file: ".adk_session.json"
  cleanup_on_exit: false
  
# Evaluation settings
evaluation:
  enable_tracing: true
  trace_sampling_rate: 1.0
  metrics_export_interval: 60
  
# Safety settings
safety:
  require_approval_for_mutations: false
  max_retries_on_error: 3
  backoff_multiplier: 2
  allow_production_fixes: true
  
# Agent-specific configurations
agents:
  coordinator:
    max_investigations_per_hour: 10
    prioritize_critical_dlqs: true
    
  dlq_monitor:
    batch_size: 10
    include_message_attributes: true
    
  investigator:
    max_messages_to_analyze: 10
    cloudwatch_lookback_minutes: 60
    
  code_fixer:
    enable_claude_subagents: true
    test_before_commit: true
    
  pr_manager:
    auto_assign_reviewers: true
    reviewers:
      - "fabio-lpd"
    
  notifier:
    voice_urgency_level: "high"
    include_queue_stats: true